version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend

  frontend:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: streamlit run app.py
    depends_on:
      - backend
    env_file:
      - .env